using FluentAssertions;
using MDNote.Core;
using MDNote.Core.Models;
using Xunit;

namespace MDNote.Core.Tests;

public class HeadingTests
{
    private readonly IMarkdownConverter _converter = new MarkdownConverter();

    [Theory]
    [InlineData(1, "#")]
    [InlineData(2, "##")]
    [InlineData(3, "###")]
    [InlineData(4, "####")]
    [InlineData(5, "#####")]
    [InlineData(6, "######")]
    public void Convert_AllHeadingLevels_ProducesCorrectTags(int level, string prefix)
    {
        var result = _converter.Convert($"{prefix} Test Heading");

        result.Html.Should().Contain($"<h{level}");
        result.Html.Should().Contain("Test Heading");
    }

    [Fact]
    public void Convert_H1_ExtractsAsTitle()
    {
        var result = _converter.Convert("# My Document Title");

        result.Title.Should().Be("My Document Title");
    }

    [Fact]
    public void Convert_MultipleHeadings_CollectsAll()
    {
        var md = "# First\n## Second\n### Third\n## Another Second";
        var result = _converter.Convert(md);

        result.Headings.Should().HaveCount(4);
        result.Headings[0].Level.Should().Be(1);
        result.Headings[0].Text.Should().Be("First");
        result.Headings[1].Level.Should().Be(2);
        result.Headings[2].Level.Should().Be(3);
        result.Headings[3].Level.Should().Be(2);
    }

    [Fact]
    public void Convert_Headings_HaveAutoGeneratedIds()
    {
        var result = _converter.Convert("## Hello World");

        result.Headings.Should().HaveCount(1);
        result.Headings[0].Id.Should().NotBeNullOrEmpty();
        result.Html.Should().Contain("id=\"");
    }

    [Fact]
    public void Convert_NoHeadings_TitleIsNull()
    {
        var result = _converter.Convert("Just some paragraph text.");

        result.Title.Should().BeNull();
        result.Headings.Should().BeEmpty();
    }
}
